# Generated by Django 5.1.5 on 2025-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogm',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
