# Generated by Django 5.1.4 on 2025-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0003_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
