# Generated by Django 5.1.4 on 2025-05-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0004_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
